UPDATE stations SET department = 'California' WHERE department = 'California, an Diego';
UPDATE stations SET department = 'Missouri' WHERE department = 'St. Louis, Missouri';
UPDATE stations SET department = 'Texas' WHERE department = 'Texas, Corpus Christi';
UPDATE stations SET department = 'Texas' WHERE department = 'Edinburg Texas';
UPDATE stations SET department = 'California' WHERE department = 'Sacramento, California';
UPDATE stations SET department = 'California' WHERE department = 'California LA';
UPDATE stations SET department = 'New Jersey' WHERE department = 'Asbury Park, New Jersey';
UPDATE stations SET department = 'Colorado' WHERE department = 'Colorado Springs CO';
UPDATE stations SET department = 'Nebraska' WHERE department = 'Nebraska City NE';
UPDATE stations SET department = 'California' WHERE department = 'Palo Alto, California';
UPDATE stations SET department = 'Florida' WHERE department = 'Miami, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'The Villages, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Tampa, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Ocala';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Miami';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, 55 West Fort Dade Avenue Brooksville';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, 4202 E Fowler Ave, Tampa, FL ';
UPDATE stations SET department = 'Florida' WHERE department = 'Port St. Lucie, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Weeki Wachee, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Hollywood, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Largo';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Clearwater';
UPDATE stations SET department = 'Iowa' WHERE department = 'Iowa City IA';
UPDATE stations SET department = 'Indiana' WHERE department = 'Indianapolis IN';
UPDATE stations SET department = 'Illinois' WHERE department = 'Chicago, Illinois';
UPDATE stations SET department = 'Illinois' WHERE department = 'Peoria, Illinois';
UPDATE stations SET department = 'Illinois' WHERE department = 'Champaign-Urbana, Illinois';
UPDATE stations SET department = 'Illinois' WHERE department = 'Pekin, Illinois';
UPDATE stations SET department = 'Kansas' WHERE department = 'Kansas City KS';
UPDATE stations SET department = 'Louisiana' WHERE department = 'LA - Louisiana';
UPDATE stations SET department = 'Michigan' WHERE department = 'MI - Michigan';
UPDATE stations SET department = 'Virginia' WHERE department = 'West Virginia';
UPDATE stations SET department = 'Michigan' WHERE department = 'Allendale Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Gaylord, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Tuscola, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Grand Rapids, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Jackson Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'South Haven, Michigan';
UPDATE stations SET department = 'New York' WHERE department = 'New York City, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Kingston, New York';
UPDATE stations SET department = 'North Carolina' WHERE department = 'Holly Springs, North Carolina';
UPDATE stations SET department = 'Oklahoma' WHERE department = 'Oklahoma City OK';
UPDATE stations SET department = 'Oklahoma' WHERE department = 'Bartlesville Oklahoma';
UPDATE stations SET department = 'Oklahoma' WHERE department = 'Wilburton Oklahoma';
UPDATE stations SET department = 'Ohio' WHERE department = 'Cleveland, Ohio';
UPDATE stations SET department = 'Ohio' WHERE department = 'Wilard, Ohio';
UPDATE stations SET department = 'Ohio' WHERE department = 'Mansfield, Ohio';
UPDATE stations SET department = 'Oregon' WHERE department = 'Bend, Oregon';
UPDATE stations SET department = 'Pennsylvania' WHERE department = 'Pennsylvania (Philadelphia)';
UPDATE stations SET department = 'Tennessee' WHERE department = ' Bristol, Tennessee';
UPDATE stations SET department = 'Texas' WHERE department = 'El Paso Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Dallas, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Austin, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Laredo, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Canyon, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Amarillo Texas';
UPDATE stations SET department = 'Virginia' WHERE department = 'Lebanon, Virginia';
UPDATE stations SET department = 'Virginia' WHERE department = 'Hampton Roads, Virginia';
UPDATE stations SET department = 'Virginia' WHERE department = 'Wheeling, West Virginia';
UPDATE stations SET department = 'Virginia' WHERE department = 'Staunton, Virginia';
UPDATE stations SET department = 'Virginia' WHERE department = 'Charlottesville, Virginia';
UPDATE stations SET department = 'Washington' WHERE department = 'Seattle Washington';
UPDATE stations SET department = 'Washington, D.C.' WHERE department = 'Washington, DC';
UPDATE stations SET department = 'Washington' WHERE department = 'Spokane, Washington';
UPDATE stations SET department = 'Washington, D.C.' WHERE department = 'Washington DC';
UPDATE stations SET department = 'Wisconsin' WHERE department = 'Brillion Wisconsin';
UPDATE stations SET department = 'Wisconsin' WHERE department = 'Dodgeville Wisconsin';
UPDATE stations SET department = 'Wisconsin' WHERE department = 'Beloit, Wisconsin';
UPDATE stations SET department = 'California' WHERE department = 'California - San Francisco';
UPDATE stations SET department = 'California' WHERE department = 'Turlock, California';
UPDATE stations SET department = 'California' WHERE department = 'Sausalito, California';
UPDATE stations SET department = 'California' WHERE department = 'Eureka, California';
UPDATE stations SET department = 'California' WHERE department = 'Oroville, California';
UPDATE stations SET department = 'California' WHERE department = 'Burbank, California';
UPDATE stations SET department = NULL WHERE department = ' ';
UPDATE stations SET department = 'California' WHERE department = 'Los Angeles CA';
UPDATE stations SET department = 'Florida' WHERE department = 'Miami FL';
UPDATE stations SET department = 'California' WHERE department = 'San Jose, California';
UPDATE stations SET department = 'Connecticut' WHERE department = 'Milford, Connecticut';
UPDATE stations SET department = 'Florida' WHERE department = 'Key West Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Palma Sola, Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Miami, MP3, 192 kbits';
UPDATE stations SET department = 'Florida' WHERE department = 'Tampa Florida';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Tampa';
UPDATE stations SET department = 'Georgia' WHERE department = 'Georgia ';
UPDATE stations SET department = 'Florida' WHERE department = 'Florida, Ft. Lauderdale';
UPDATE stations SET department = 'Georgia' WHERE department = 'Cordele, Georgia';
UPDATE stations SET department = 'Iowa' WHERE department = 'Fort Dodge, Iowa';
UPDATE stations SET department = 'Indiana' WHERE department = 'Indiana ';
UPDATE stations SET department = 'Indiana' WHERE department = 'indiana';
UPDATE stations SET department = 'Iowa' WHERE department = 'Mason City Iowa';
UPDATE stations SET department = 'Kansas' WHERE department = 'Kansas, ';
UPDATE stations SET department = 'Michigan' WHERE department = 'Livonia, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Detroit, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Tawas City Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Muskegon, Michigan';
UPDATE stations SET department = 'Mississippi' WHERE department = 'Grenada, Mississippi';
UPDATE stations SET department = 'Michigan' WHERE department = 'Bad Axe Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Holland, Michigan';
UPDATE stations SET department = 'Michigan' WHERE department = 'Ann Arbor Michigan';
UPDATE stations SET department = 'Minnesota' WHERE department = 'Minnesota ';
UPDATE stations SET department = 'Missouri' WHERE department = 'Mexico, Missouri';
UPDATE stations SET department = 'New Jersey' WHERE department = 'Edison, New Jersey';
UPDATE stations SET department = 'New Jersey' WHERE department = 'New Jersey ';
UPDATE stations SET department = 'New York' WHERE department = 'Buffalo, New York';
UPDATE stations SET department = 'New York' WHERE department = 'NEW YORK';
UPDATE stations SET department = 'New York' WHERE department = 'Ellenville, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Poughkeepsie, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Warwick, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Monticello, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Brooklyn, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Ithaca, New York';
UPDATE stations SET department = 'New York' WHERE department = 'Binghamton New York';
UPDATE stations SET department = 'Ohio' WHERE department = 'Dayton, OHIO';
UPDATE stations SET department = 'North Carolina' WHERE department = 'North Carolina ';
UPDATE stations SET department = 'North Carolina' WHERE department = 'Mount Airy, North Carolina';
UPDATE stations SET department = 'Ohio' WHERE department = 'Clyde, Ohio';
UPDATE stations SET department = 'Ohio' WHERE department = 'Westerville, Ohio';
UPDATE stations SET department = 'Ohio' WHERE department = 'Conneaut, Ohio';
UPDATE stations SET department = 'Ohio' WHERE department = 'Blacklick, Ohio';
UPDATE stations SET department = 'Oregon' WHERE department = 'Milwaukie Oregon';
UPDATE stations SET department = 'Oregon' WHERE department = 'OREGON';
UPDATE stations SET department = 'Texas' WHERE department = 'texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Houston, Texas';
UPDATE stations SET department = 'South Dakota' WHERE department = 'Gregory, South Dakota';
UPDATE stations SET department = 'South Carolina' WHERE department = 'Greenville, South Carolina';
UPDATE stations SET department = 'Utah' WHERE department = 'utah';
UPDATE stations SET department = 'Texas' WHERE department = 'Irving, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Texas ';
UPDATE stations SET department = 'Texas' WHERE department = 'Denton, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'Floydada, Texas';
UPDATE stations SET department = 'Texas' WHERE department = 'TEXAS';
UPDATE stations SET department = 'Washington' WHERE department = 'Tacoma, Washington';
UPDATE stations SET department = 'Washington' WHERE department = 'Seattle, Washington';