UPDATE stations SET language = 'English' WHERE language = 'english';
UPDATE stations SET language = 'English' WHERE language = 'american english';
UPDATE stations SET language = 'Spanish' WHERE language = 'spanish';
UPDATE stations SET language = 'English' WHERE language = 'englisg';
UPDATE stations SET language = 'English, Spanish' WHERE language = 'english spanish';
UPDATE stations SET language = 'French' WHERE language = 'Français';
UPDATE stations SET language = 'Punjabi' WHERE language = 'punjabi';
UPDATE stations SET language = 'Portuguese' WHERE language = 'portuguese';
UPDATE stations SET language = 'Russian' WHERE language = 'russian';
UPDATE stations SET language = 'Aboriginal Languages' WHERE language = 'aboriginal languages';
UPDATE stations SET language = 'English' WHERE language = 'englsh';
UPDATE stations SET language = 'Serbian' WHERE language = 'serbian';
UPDATE stations SET language = 'English' WHERE language = 'engilsh';
UPDATE stations SET language = 'English' WHERE language = 'englsih';
UPDATE stations SET language = 'English' WHERE language = 'english/';
UPDATE stations SET language = 'Korean' WHERE language = 'korean';
UPDATE stations SET language = 'Thai' WHERE language = 'thai';
UPDATE stations SET language = 'German' WHERE language = 'deutsch fränkisch';
UPDATE stations SET language = 'Chinese' WHERE language = 'chinese';
UPDATE stations SET language = 'English' WHERE language = '#english';
UPDATE stations SET language = 'Various Languages' WHERE language = 'various languages';
UPDATE stations SET language = 'Persian' WHERE language = 'persian';
UPDATE stations SET language = 'Armenian' WHERE language = 'armenian';
UPDATE stations SET language = 'Haitian Creole' WHERE language = 'haitian creole';
UPDATE stations SET language = 'Indonesian' WHERE language = 'bahasa indonesia';
UPDATE stations SET language = 'Haitian Creole' WHERE language = 'creole';
UPDATE stations SET language = 'Afrikaans' WHERE language = 'afrikaans';
UPDATE stations SET language = 'Japanese' WHERE language = 'japanese';
UPDATE stations SET language = 'Cantonese' WHERE language = 'cantonese';
UPDATE stations SET language = 'Italian' WHERE language = 'italian';
UPDATE stations SET language = 'German' WHERE language = 'german';
UPDATE stations SET language = 'Bisaya' WHERE language = 'bisaya';
UPDATE stations SET language = 'English' WHERE language = 'english uk';